name: Build and Push to ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      # ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
            registry-type: public
            region: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image
        run: |
          docker build -t akwasi-kusi-appiah-dockerECR:latest .
          docker tag $akwasi-kusi-appiah-dockerECR:latest $akwasi-kusi-appiah-dockerECR:latest
          docker push $akwasi-kusi-appiah-dockerECR:latest

